// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApplication.Data;

#nullable disable

namespace ToDoApplication.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20230413030330_Remove attributes from migration")]
    partial class Removeattributesfrommigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("ToDoApplication.Models.ToDo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Title = "Prepare Breakfast",
                            CompletionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = true
                        },
                        new
                        {
                            Title = "Eat",
                            CompletionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false
                        },
                        new
                        {
                            Title = "Clean Room",
                            CompletionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false
                        },
                        new
                        {
                            Title = "Do Laundry",
                            CompletionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsComplete = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
