// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApplication.Data;

#nullable disable

namespace ToDoApplication.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20230416035240_Create new migration")]
    partial class Createnewmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("ToDoApplication.Models.ToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsComplete = false,
                            Title = "Prepare Breakfast"
                        },
                        new
                        {
                            ID = 2,
                            IsComplete = false,
                            Title = "Eat"
                        },
                        new
                        {
                            ID = 3,
                            IsComplete = false,
                            Title = "Clean Room"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
